#!/usr/bin/env python

import sys, os
import urllib2
from BeautifulSoup import BeautifulSoup

def msg():
    html = urllib2.urlopen('http://whatthecommit.com/').read()
    return BeautifulSoup(html).find(id='content').p.string.strip()

if __name__ == '__main__':
    do_it = sys.stdout.write if '--wimp' in sys.argv else os.system
    do_it('git commit -a -m "%s"' % msg().replace(r'"', r'\"'))
