#!/usr/bin/env python

import sys, os
import urllib2

def msg():
    return urllib2.urlopen('http://whatthecommit.com/index.txt').read().strip()

if __name__ == '__main__':
    do_it = sys.stdout.write if '--wimp' in sys.argv else os.system
    do_it('git commit -a -m "%s"' % msg().replace(r'"', r'\"'))
